### ISSUE TITLE
Rework encrypted chunked extension

### ISSUE THREAD

**Issue by robin-nitrokey** [trussed-dev/trussed-staging#20]
Currently, the `ChunkedExtension` gains additional syscalls if the `encrypted-chunked` feature is enabled.  This has the downside that enabling the feature in one crate can break another crate that does not have the feature enabled.  I see two alternatives:
1. Introduce an `EncryptedChunkedExtension` that is still optional in the backend.  This would mean that runners could save some resources if they don’t need the encrypted calls.
2. Remove the feature gate and always provide the encryption functions in `ChunkedExtension`.  In practice, `opcard` requires `encrypted-chunked`, so it will always be enabled in the firmware and the use case for a separate extension is only theoritical.

I would go with (2).  What do you prefer @sosthene-nitrokey?

**Comment by sosthene-nitrokey** [comment]
I would go with 2 also.

We could also put the implementation itself behind a feature-flag if we ever need to make it optional again.
